name: zinnia
version: 1

handlers:
- url: /static/
  static_path: static
  gzip: on
- url: /robots.txt
  static_path: robots.txt
- url: /favicon.ico
  static_path: favicon.ico

libraries:
- name: "django"
  version: "1.5"